version: '3.8'

services:
  postgres-db:
      image: postgres:15-alpine
      container_name: sie_postgres_db
      restart: always
      environment:
        POSTGRES_USER: sie_user
        POSTGRES_PASSWORD: sie_password
        POSTGRES_DB: sie_management_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
